#!/usr/bin/env bash

# Install Ansible (Source: pip)
## Update system:
sudo apt-get update && \
  sudo apt-get upgrade -y

## Install prerequisites:
sudo apt-get install -y \
  python-pip \
  python-dev

## Add Docker’s official GPG key:
sudo -H pip install ansible=="${version_ansible}"
