#!/usr/bin/env bash

# Install prerequisites:
sudo apt-get update
sudo apt-get install -y unzip

# Fetch Packer from upstream Hashicorp:
curl -o /tmp/terraform_${version_terraform}_${flexbuild_type}_${flexbuild_arch}.zip https://releases.hashicorp.com/terraform/${version_terraform}/terraform_${version_terraform}_${flexbuild_type}_${flexbuild_arch}.zip

# Unzip the binary:
unzip /tmp/terraform_${version_terraform}_${flexbuild_type}_${flexbuild_arch}.zip -d /tmp/

# Move binary to PATH location:
sudo mv terraform /usr/local/bin/terraform
sudo chown root:root /usr/local/bin/terraform

# Cleanup:
rm -rf /tmp/terraform_${version_terraform}_${flexbuild_type}_${flexbuild_arch}.zip
